DROP TABLE ENROLMENT;
DROP TABLE SUBJECT_TBL;
DROP TABLE STUDENT_TBL;

CREATE TABLE STUDENT_TBL(
    STU_NO VARCHAR2(10 BYTE) NOT NULL,
    STU_NAME VARCHAR2(20 BYTE),
    AGE NUMBER,
    CONSTRAINT PK_STU PRIMARY KEY(STU_NO)
);

CREATE TABLE SUBJECT_TBL(
    SUB_CODE VARCHAR2(2 BYTE),
    SUB_NAME VARCHAR2(10 BYTE),
    PROF VARCHAR2(15 BYTE),
    CONSTRAINT PK_SUB PRIMARY KEY(SUB_CODE)
);

CREATE TABLE ENROLMENT(
    REG_NO NUMBER,
    STU_NO VARCHAR2(10 BYTE) NOT NULL,
    SUB_CODE VARCHAR2(2 BYTE),
    CONSTRAINT PK_ENR PRIMARY KEY(REG_NO),
    CONSTRAINT FK_ENR_ST FOREIGN KEY(STU_NO) REFERENCES STUDENT_TBL(STU_NO),
    CONSTRAINT FK_ENR_SUB FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT_TBL(SUB_CODE)
);